### ISSUE TITLE
PKI sleutel deponeren?

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [Logius-standaarden/Digikoppeling-Handreiking-Adressering-en-Routering#3]
Onder het kopje "Kunnen in certificaat en header verschillende OIN gebruikt worden" staat deze tekst " of bij de SAAS-provider een eigen certificaat deponeren"

Zoals besproken in het laatste TO is beveiligingstechnisch niet in de haak. Dat als alsof je je bankpas met code bij een Russisch hotel moet deponeren, en de KGB stiekem je bankrekening kan plunderen. 

Vertrouwen is goed, controleren is beter. Dat is waarom Edukoppeling een andere oplossing heeft geformuleerd. Hierin de verwerker zelf geïdentificeerd en zijn er aanvullende maatregelen om de controleren of die inderdaad gemachtigd is.  In Edukoppeling is er een centrale oplossing met een machtigingenregister, maar dat kan ook decentraal.

Voorheen was het misschien technisch noodzaak om te deponeren, maar dat is nu aantoonbaar anders. Ik opteer voor:

1. De genoemde tekst doorstrepen
2. Opnemen dat deze optie niet veilig is

**Comment by PHaasnoot** [comment]
Zie ook Analyse knelpunten Routering en Intermediairs
https://github.com/Logius-standaarden/Digikoppeling-Handreiking-Adressering-en-Routering/blob/main/documenten/Analyse_knelpunten_Routering_Intermediairs.md
Hierin wordt nadeel van 'eigen certificaat deponeren' aangegeven

Een optie is wel dmv gebruik suboin een certificaat met een scope specifiek voor een bepaalde dienst aan de SAAS-provider te verstrekken.

De tekst zal worden aangepast in de handreiking (en besproken in het Technisch Overleg Digikoppeling)
